# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CRPS divergence for uniform distribution
#'
#' @param x vector of PIT values.
#'
#' @useDynLib TailCalibration, .registration = TRUE
#' @importFrom Rcpp evalCpp
#'
#' @export
crps_div <- function(x) {
    .Call(`_TailCalibration_crps_div`, x)
}

